### ISSUE TITLE
Pesquisar ferramentas de QUIZZ 

### ISSUE THREAD

**Issue by vicmagpac** [EscolaDeSaudePublica/BancoDeIDeias#20]
- Gerenciamento de itens
- Gerenciamento de Usuários
- Gerenciamento de provas
- Gerenciamento de provas em áreas (temas e subtemas)
- De preferências tecnologias recentes

**Comment by vicmagpac** [comment]
https://savsoftquiz.com/web/
https://www.techjockey.com/blog/7-free-open-source-exam-software

**Comment by ItaloRod** [comment]
## https://www.questionpro.com/

### prós
* Free com período de testes
* Unlimited surveys
* Unlimited questions
* Unlimited responses - You can collect unlimited responses in your Essentials account, however 
* each survey is limited to a maximum of 1,000 responses. 
* Data exports (xls & csv)
* Dashboard Analytics
* Customized 

### contras
* Sem gerenciamento de usuários bem definidos
* E-mail Invites Only - Upgrade Required 

---------------------------------------------------
## https://docs.google.com/forms
---------------------------------------------------
## https://moodle.org/?lang=pt_br
--------------------------------------------------
## https://formtools.org/ (Open - Source)

**Comment by victorMagalhaesPacheco** [comment]
https://www.techjockey.com/blog/7-free-open-source-exam-software

**Comment by uira** [comment]
### Pesquisando aqui sobre Moodle:
- https://stackoverflow.com/questions/42148306/moodle-quiz-rest-api
- https://docs.moodle.org/dev/Web_service_API_functions
- https://docs.moodle.org/dev/Quiz_support_in_the_Mobile_app
- https://docs.moodle.org/33/en/Using_web_services

https://danielneis.github.io/moodleparadesenvolvedores/

**Outras referências:**
- https://github.com/ozanerturk/telegram-quiz-bot
- https://moodle.org/plugins/message_telegram
  - https://github.com/PoetOS/moodle-message_output_telegram

-
